# Generated by Django 5.0.7 on 2024-07-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_user_groups_alter_user_user_permissions_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lessons', models.ManyToManyField(blank=True, to='courses.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(blank=True, to='courses.module'),
        ),
    ]
