# Generated by Django 5.0.7 on 2024-07-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_lessons_module_course_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='courses.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(to='courses.lesson'),
        ),
    ]
