# Generated by Django 5.1.1 on 2024-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_module_description_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='courses.quiz'),
        ),
    ]
